apiVersion: v1
data:
  default.conf: |
    server {
        server_name prometheus;
        listen 9443 ssl;

        ssl_certificate /opt/bitnami/nginx/data/certs/fullchain.pem;
        ssl_certificate_key /opt/bitnami/nginx/data/certs/privkey.pem;

        auth_basic "Restricted Access";
        auth_basic_user_file /opt/bitnami/nginx/data/auth/.htpasswd;

        location / {
            proxy_pass http://prometheus:9090;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: nginx-config
