apiVersion: v1
kind: Pod
metadata: 
  name: prom-nginx 
  annotations: 
    io.podman.annotations.publish.ports: "true"
spec:
  containers:
    - name: nginx
      image: docker.io/bitnami/nginx:latest
      ports:
        - containerPort: 9443 
          hostPort: 9443
        - containerPort: 9000 
          hostPort: 9000
      volumeMounts:
        - name: nginx-conf
          mountPath: /opt/bitnami/nginx/conf/server_blocks
        - name: nginx-certs
          mountPath: /opt/bitnami/nginx/data/certs
        - name: nginx-auth
          mountPath: /opt/bitnami/nginx/data/auth
  volumes:
    - name: nginx-conf
      configMap:
        name: nginx-config
    - name: nginx-auth
      hostPath:
        path: /home/prometheus/nginx/auth 
        type: Directory
    - name: nginx-certs
      hostPath: 
        path: /home/prometheus/nginx/certs
        type: Directory

