apiVersion: v1
kind: Pod
metadata: 
  name: prometheus
  annotations: {} 
spec:
  containers:
    - name: prometheus
      image: docker.io/bitnami/prometheus:latest
      command: ["/opt/bitnami/prometheus/bin/prometheus"]
      args: ["--config.file=/opt/bitnami/prometheus/conf/prometheus.yml",
             "--storage.tsdb.path=/opt/bitnami/prometheus/data",
             "--storage.tsdb.retention.time=10y",
             "--web.console.libraries=/opt/bitnami/prometheus/conf/console_libraries",
             "--web.console.templates=/opt/bitnami/prometheus/conf/consoles"
             ]
      ports:
        - containerPort: 9090
      volumeMounts:
        - name: prometheus-data
          mountPath: /opt/bitnami/prometheus/data
        - name: prometheus-conf
          mountPath: /opt/bitnami/prometheus/conf/prometheus.yml
          subPath: prometheus.yml
        - name: prometheus-conf
          mountPath: /opt/bitnami/prometheus/conf/prometheus_rules.yml
          subPath: prometheus_rules.yml
  volumes:
    - name: prometheus-data
      hostPath:
        path: /home/prometheus/prometheus
        type: Directory
    - name: prometheus-conf
      configMap:
        name: confmap-prom
          #      hostPath: 
          #        path: /home/prometheus/prometheus/prometheus.yml
          #        type: File
