apiVersion: v1
kind: Pod
metadata: 
  name: prom-specv-exp 
spec:
  containers:
    - name: exporter
      image: localhost/exporter-v7kg2
      args: ['--config.file=/etc/specvexporter/spectrumVirtualize.yml']
      ports:
        - containerPort: 9119 
      volumeMounts:
        - name: exp-conf
          mountPath: /etc/specvexporter
  volumes:
    - name: exp-conf
      configMap:
        name: exporter-config
